project_id = "rwhpbxzattitinywvgpy"

[functions.generate-video-script]
verify_jwt = true

[functions.generate-storyboard]
verify_jwt = true

[functions.generate-share-link]
verify_jwt = true

[functions.export-video]
verify_jwt = true